import json
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score


# -----------------------------------------------------------
# Utilities
# -----------------------------------------------------------

def load_synthetic_dataset(
    csv_path: str = "synthetic_missingness.csv",
    columns_json: str = "synthetic_missingness_columns.json",
    mech_json: str = "synthetic_missingness_mechanisms.json",
) -> Tuple[pd.DataFrame, Dict[str, str]]:
    """
    Load the synthetic dataset and metadata generated by
    generate_synthetic_missingness.py.

    Returns:
        df: pandas DataFrame with NaNs
        true_mechanisms: dict {col_name -> mechanism}
    """
    # Load column order
    with open(columns_json, "r") as f:
        col_meta = json.load(f)
    col_names = col_meta["columns"]

    # Load CSV into DataFrame
    df = pd.read_csv(csv_path, header=None)
    df.columns = col_names

    # Load ground-truth mechanisms
    with open(mech_json, "r") as f:
        true_mechanisms = json.load(f)

    return df, true_mechanisms


def make_missing_indicator(col: pd.Series) -> np.ndarray:
    """
    Given a pandas Series, return a 1D numpy array R where:
      R[i] = 1 if col[i] is NaN
             0 otherwise
    """
    return col.isna().astype(int).to_numpy()


def chi_square_mcar_test(
    R: np.ndarray,
    predictors: pd.DataFrame,
    n_bins: int = 4,
    alpha: float = 0.05,
) -> float:
    """
    Perform a simple MCAR check: for each predictor column,
    bin it into n_bins quantiles and run a chi-square test
    between the missingness indicator R and the binned predictor.

    Returns:
        min_pvalue: minimum p-value across predictors
    """
    pvalues: List[float] = []
    R_series = pd.Series(R)

    for col_name in predictors.columns:
        col = predictors[col_name]

        # Drop rows where predictor is NaN
        mask = ~col.isna()
        if mask.sum() == 0:
            continue

        R_valid = R_series[mask]
        x_valid = col[mask]

        # Bin the predictor into quantiles
        try:
            # qcut may fail if too few unique values
            binned = pd.qcut(x_valid, q=n_bins, duplicates="drop")
        except ValueError:
            # Fallback: no binning, skip this predictor
            continue

        contingency = pd.crosstab(R_valid, binned)

        # We need at least a 2 x k table
        if contingency.shape[0] < 2 or contingency.shape[1] < 2:
            continue

        try:
            chi2, p, dof, expected = chi2_contingency(contingency)
            pvalues.append(p)
        except Exception:
            # Any numerical issue, just skip this predictor
            continue

    if not pvalues:
        # If we couldn't compute any test, be conservative: return 0.0
        return 0.0

    return float(np.min(pvalues))


def logistic_mar_score(
    R: np.ndarray,
    predictors: pd.DataFrame,
    max_iter: int = 200,
) -> float:
    """
    Fit a logistic regression model R ~ predictors and compute the AUC.
    We drop rows with any missing in predictors.

    Returns:
        auc: ROC AUC score in [0, 1]; if not computable, returns 0.5
    """
    # Combine R and predictors into one DataFrame to drop NaNs jointly
    data = predictors.copy()
    data["R"] = R

    data = data.dropna()
    if data.shape[0] < 20:
        # Not enough data to fit a model
        return 0.5

    y = data["R"].to_numpy()
    X = data.drop(columns=["R"]).to_numpy()

    # If only one class in R, AUC is undefined
    if len(np.unique(y)) < 2:
        return 0.5

    try:
        model = LogisticRegression(
            solver="lbfgs",
            max_iter=max_iter,
        )
        model.fit(X, y)
        # Use predicted probabilities for class 1
        prob = model.predict_proba(X)[:, 1]
        auc = roc_auc_score(y, prob)
        return float(auc)
    except Exception:
        return 0.5


# -----------------------------------------------------------
# Main detection logic
# -----------------------------------------------------------

def detect_missing_mechanism_for_column(
    df: pd.DataFrame,
    col_name: str,
    alpha: float = 0.05,
    auc_thresh: float = 0.7,
    base_features: List[str] = None,
) -> str:
    """
    Classify the missingness mechanism for a single column:
    returns one of: "none", "MCAR", "MAR", "MNAR".
    """

    col = df[col_name]
    R = make_missing_indicator(col)

    # Case 1: no missing at all
    if R.sum() == 0:
        return "none"

    # Choose predictors:
    # if base_features is given, use those (and drop col_name if present).
    # otherwise, use all other columns except the target column itself.
    if base_features is not None:
        predictors_cols = [c for c in base_features if c != col_name]
    else:
        predictors_cols = [c for c in df.columns if c != col_name]

    predictors = df[predictors_cols]

    # 1) MCAR check via chi-square tests
    min_pvalue = chi_square_mcar_test(R, predictors, alpha=alpha)
    # If all tests show no dependence (min p > alpha) -> MCAR
    if min_pvalue > alpha:
        return "MCAR"

    # 2) MAR vs MNAR check via logistic regression on observed predictors
    auc = logistic_mar_score(R, predictors)

    if auc >= auc_thresh:
        return "MAR"

    # 3) Fallback: MNAR
    return "MNAR"


def detect_missing_mechanisms_dataset(
    df: pd.DataFrame,
    alpha: float = 0.05,
    auc_thresh: float = 0.7,
    base_features: List[str] = None,
) -> Dict[str, str]:
    """
    Run missingness mechanism detection for all columns in df.

    Returns:
        pred_mechanisms: dict {col_name -> predicted mechanism}
    """
    pred: Dict[str, str] = {}
    for col in df.columns:
        mech = detect_missing_mechanism_for_column(
            df,
            col,
            alpha=alpha,
            auc_thresh=auc_thresh,
            base_features=base_features,
        )
        pred[col] = mech
    return pred


def compare_with_ground_truth(
    true_mech: Dict[str, str],
    pred_mech: Dict[str, str],
) -> pd.DataFrame:
    """
    Build a small summary table comparing true vs predicted mechanisms.
    """
    rows = []
    for col in pred_mech.keys():
        rows.append(
            {
                "column": col,
                "true": true_mech.get(col, "N/A"),
                "predicted": pred_mech[col],
                "correct": true_mech.get(col, "N/A") == pred_mech[col],
            }
        )
    return pd.DataFrame(rows)


def confusion_matrix_mechanisms(
    true_mech: Dict[str, str],
    pred_mech: Dict[str, str],
) -> pd.DataFrame:
    """
    Build a confusion matrix (true vs predicted mechanisms).
    """
    data = {
        "true": [],
        "predicted": [],
    }
    for col, t in true_mech.items():
        if col not in pred_mech:
            continue
        data["true"].append(t)
        data["predicted"].append(pred_mech[col])
    df_res = pd.DataFrame(data)
    cm = pd.crosstab(df_res["true"], df_res["predicted"])
    return cm


# -----------------------------------------------------------
# Main entry point
# -----------------------------------------------------------

if __name__ == "__main__":
    # 1) Load synthetic data and ground truth
    df, true_mech = load_synthetic_dataset()

    # Optional: define which columns we treat as "base features" for MAR logistic
    base_features = None  # they have no missing by construction

    # 2) Run detection
    pred_mech = detect_missing_mechanisms_dataset(
        df,
        alpha=0.05,
        auc_thresh=0.6,
        base_features=base_features,
    )

    # 3) Show per-column comparison
    comparison = compare_with_ground_truth(true_mech, pred_mech)
    print("\nPer-column true vs predicted mechanisms:")
    print(comparison.to_string(index=False))

    accuracy = comparison["correct"].mean()
    print(f"\nOverall accuracy: {accuracy:.3f}")

    # 4) Show confusion matrix
    print("\nConfusion matrix (true vs predicted):")
    print(confusion_matrix_mechanisms(true_mech, pred_mech))

    # 5) Detailed diagnostics: p-values and AUC per column
    print("\nDetailed diagnostics per column:")
    rows = []
    for col in df.columns:
        col_series = df[col]
        R = make_missing_indicator(col_series)

        # predictors: base features (x1,x2,x3) se ci sono, altrimenti tutte le altre
        if base_features is not None:
            predictors_cols = [c for c in base_features if c != col]
        else:
            predictors_cols = [c for c in df.columns if c != col]

        predictors = df[predictors_cols]

        min_p = chi_square_mcar_test(R, predictors, alpha=0.05)
        auc = logistic_mar_score(R, predictors)

        rows.append(
            {
                "column": col,
                "true": true_mech.get(col, "N/A"),
                "predicted": pred_mech[col],
                "min_pvalue": min_p,
                "auc": auc,
            }
        )

    diag_df = pd.DataFrame(rows)
    print(diag_df.to_string(index=False, float_format=lambda x: f"{x:.3f}"))